#!/bin/bash
time=''
H=''
M=''
N=''
c=''
countofstr=''
echo Ваши действия
echo 1. создание
echo 2. редактирование
echo 3. удаление
echo 4. список будильников
read N
if ((N<=0)) || ((N>4)); then
echo input error
exit
fi
case $N in 
1)
echo Введите время в формате HH MM
read H M
echo $H $M 
echo ''$M' '$H' * * * /home/jackson/alarms/alarm.sh' >>cronch
crontab < cronch
;;
2)
echo Введите время редактируемого будильника
sed -i 's/\([0-9]*\) \([0-9]*\)/\2 \1/' cronch
count=$(wc -l < cronch)
echo $count
for ((i=1; i <= $count; i++))
do
sed -i ''$i's/^/'$i'-/' cronch
done
d="$(cut cronch -c 1-7)"
echo "$d"
echo Выберите редактируемый будильник
read str
echo введите время
read H M
sed -i ''$str's%.*%'$str'-'$H' '$M' * * * /home/jackson/alarms/alarm.sh%g' cronch
sed -i 's/^..//' cronch
sed -i 's/\([0-9]*\) \([0-9]*\)/\2 \1/' cronch
crontab < cronch
;;
3)
sed -i 's/\([0-9]*\) \([0-9]*\)/\2 \1/' cronch
count=$(wc -l < cronch)
echo $count
for ((i=1; i <= $count; i++))
do
sed -i ''$i's/^/'$i'-/' cronch
done
d="$(cut cronch -c 1-7)"
echo "$d"
echo выберите ненужный будильник
read str
sed -i ''$str'd' cronch
sed -i 's/^..//' cronch
sed -i 's/\([0-9]*\) \([0-9]*\)/\2 \1/' cronch
crontab < cronch
;;
4)
cat cronch
;;
esac
