#!/bin/bash
direct=''
name=''
subname=''
count=''
fname=''
echo -n "Введите место расположения папок"
read direct
	if [ -z "$direct" ] ; then
		echo input error
	exit
	fi

echo -n "Введитe название папок"
read name
	if [ -z "$name" ] ; then
		echo input error
	exit
	fi
	if [[ "$name" == */* ]] ; then
		echo input error
		exit
	fi
echo -n "Введитe количество папок"
read count
	if [ -z "$count" ] ; then
		echo input error
	exit
	fi
	if [[ $count -le 0 || $count -ge 150 ]] ; then
		echo input error
		exit
	fi
echo -n "Введитe название подпапок"
read subname
	if [ -z "$subname" ] ; then
		echo input error
	exit
	fi
	if [[ "$subname" == */* ]] ; then
		echo input error
		exit
	fi
echo -n "Введитe название файлов"
read fname
	if [ -z "$fname" ] ; then
		echo input error
	exit
	fi
	if [[ "$fname" == */* ]] ; then
		echo input error
		exit
	fi
for ((i = 1 ; i <= $count; i++)); do
	mkdir $direct/$name$i
	for ((j= 1; j <= 10; j++)); do
		mkdir $direct/$name$i/$subname$j
		for ((k = 1; k<=20; k++)); do
			touch $direct/$name$i/$subname$j/$fname$k
		done
	done
done
